---
title: "MindBoggle Results"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
outlier <- function(dt, var)
{
    var_name <- eval(substitute(dt[[var]]), eval(dt))
    tot <- sum(!is.na(var_name))
    na1 <- sum(is.na(var_name))
    m1 <- mean(var_name, na.rm = T)
    par(mfrow = c(2, 2), oma = c(0, 0, 3, 0))
    boxplot(var_name, main = "With outliers")
    hist(var_name, main = "With outliers", xlab = NA, ylab = NA)
    outlier <- boxplot.stats(var_name)$out
    mo <- mean(outlier)
    var_name <- ifelse(var_name %in% outlier, NA, var_name)
    boxplot(var_name, main = "Without outliers")
    hist(var_name, main = "Without outliers", xlab = NA, ylab = NA)
    title("Outlier Check", outer = TRUE)
    na2 <- sum(is.na(var_name))
    message("Outliers identified: ", na2 - na1, " from ", tot, " observations")
    message("Proportion (%) of outliers: ", (na2 - na1)/tot * 100)
    message("Mean of the outliers: ", mo)
    m2 <- mean(var_name, na.rm = T)
    message("Mean without removing outliers: ", m1)
    message("Mean if we remove outliers: ", m2)
    dt[as.character(var)] <- var_name
    assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
    return(invisible(dt))
    message("Outliers successfully removed", "\n")
}
```

## Cortical Thickness

```{r, include=FALSE}
setwd("/Volumes/wasatch/data/stats/R21/mindboggle/")
mydata = read.table("thickinthehead_per_freesurfer_cortex_label.csv", sep = ",", 
    header = T)
clist = colnames(mydata)[3:length(mydata)]
for (i in clist)
{
    outlier(mydata, i)
}
demogr = read.table("/Volumes/wasatch/data/analyses/R21/demographics/R21_demographics.txt", 
    sep = ",", header = T)
mydata = merge(demogr, mydata, by = "studyid", all.y = T)
mydata$group = relevel(mydata$group, "oi")
table = data.frame()
for (i in 6:(length(mydata)))
{
    oimean = colMeans(subset(mydata, group == "oi")[i], na.rm = T)
    oisd = sd(subset(mydata, group == "oi")[[i]], na.rm = T)
    tbimean = colMeans(subset(mydata, group == "tbi")[i], na.rm = T)
    tbisd = sd(subset(mydata, group == "tbi")[[i]], na.rm = T)
    fit = lm(mydata[[i]] ~ group + age, data = mydata)
    fvalue = anova(fit)[[4]][1]
    pvalue = round(anova(fit)[[5]][1], 4)
    padjvalue = p.adjust(round(anova(fit)[[5]][1], 4), method = "fdr", n = 78)
    temp = cbind(oimean, oisd, tbimean, tbisd, fvalue, pvalue, padjvalue)
    table = rbind(table, temp)
}
table <- table[order(table$pvalue), ]
```

```{r, echo = FALSE}
library(knitr)
kable(table, align = "ccccccc", digits = 2, col.names = c("OI mean", "OI SD", 
    "TBI mean", "TBI SD", "F", "p (unadj)", "p (FDR)"))
```

\pagebreak

## Volume

```{r, include=FALSE}
setwd("/Volumes/wasatch/data/stats/R21/mindboggle/")
mydata = read.table("volume_per_freesurfer_label.csv", sep = ",", 
    header = T)
clist = colnames(mydata)[3:length(mydata)]
for (i in clist)
{
    outlier(mydata, i)
}
demogr = read.table("/Volumes/wasatch/data/analyses/R21/demographics/R21_demographics.txt", 
    sep = ",", header = T)
mydata = merge(demogr, mydata, by = "studyid", all.y = T)
mydata$group = relevel(mydata$group, "oi")
table = data.frame()
for (i in 6:(length(mydata)))
{
    oimean = colMeans(subset(mydata, group == "oi")[i], na.rm = T)
    oisd = sd(subset(mydata, group == "oi")[[i]], na.rm = T)
    tbimean = colMeans(subset(mydata, group == "tbi")[i], na.rm = T)
    tbisd = sd(subset(mydata, group == "tbi")[[i]], na.rm = T)
    fit = lm(mydata[[i]] ~ group + age, data = mydata)
    fvalue = anova(fit)[[4]][1]
    pvalue = round(anova(fit)[[5]][1], 4)
    padjvalue = p.adjust(round(anova(fit)[[5]][1], 4), method = "fdr", n = 78)
    temp = cbind(oimean, oisd, tbimean, tbisd, fvalue, pvalue, padjvalue)
    table = rbind(table, temp)
}
table <- table[order(table$pvalue), ]
```

```{r, echo = FALSE}
library(knitr)
kable(table, align = "ccccccc", digits = 2, col.names = c("OI mean", "OI SD", 
    "TBI mean", "TBI SD", "F", "p (unadj)", "p (FDR)"))
```

\pagebreak

## Area

```{r, include=FALSE}
setwd("/Volumes/wasatch/data/stats/R21/mindboggle/")
mydata = read.table("area_per_gyrus_label.csv", sep = ",", 
    header = T)
clist = colnames(mydata)[3:length(mydata)]
for (i in clist)
{
    outlier(mydata, i)
}
demogr = read.table("/Volumes/wasatch/data/analyses/R21/demographics/R21_demographics.txt", 
    sep = ",", header = T)
mydata = merge(demogr, mydata, by = "studyid", all.y = T)
mydata$group = relevel(mydata$group, "oi")
table = data.frame()
for (i in 6:(length(mydata)))
{
    oimean = colMeans(subset(mydata, group == "oi")[i], na.rm = T)
    oisd = sd(subset(mydata, group == "oi")[[i]], na.rm = T)
    tbimean = colMeans(subset(mydata, group == "tbi")[i], na.rm = T)
    tbisd = sd(subset(mydata, group == "tbi")[[i]], na.rm = T)
    fit = lm(mydata[[i]] ~ group + age, data = mydata)
    fvalue = anova(fit)[[4]][1]
    pvalue = round(anova(fit)[[5]][1], 4)
    padjvalue = p.adjust(round(anova(fit)[[5]][1], 4), method = "fdr", n = 78)
    temp = cbind(oimean, oisd, tbimean, tbisd, fvalue, pvalue, padjvalue)
    table = rbind(table, temp)
}
table <- table[order(table$pvalue), ]
```

```{r, echo = FALSE}
library(knitr)
kable(table, align = "ccccccc", digits = 2, col.names = c("OI mean", "OI SD", 
    "TBI mean", "TBI SD", "F", "p (unadj)", "p (FDR)"))
```

\pagebreak

## Travel Depth

```{r, include=FALSE}
setwd("/Volumes/wasatch/data/stats/R21/mindboggle/")
mydata = read.table("travel_depth_per_gyrus_label.csv", sep = ",", 
    header = T)
clist = colnames(mydata)[3:length(mydata)]
for (i in clist)
{
    outlier(mydata, i)
}
demogr = read.table("/Volumes/wasatch/data/analyses/R21/demographics/R21_demographics.txt", 
    sep = ",", header = T)
mydata = merge(demogr, mydata, by = "studyid", all.y = T)
mydata$group = relevel(mydata$group, "oi")
table = data.frame()
for (i in 6:(length(mydata)))
{
    oimean = colMeans(subset(mydata, group == "oi")[i], na.rm = T)
    oisd = sd(subset(mydata, group == "oi")[[i]], na.rm = T)
    tbimean = colMeans(subset(mydata, group == "tbi")[i], na.rm = T)
    tbisd = sd(subset(mydata, group == "tbi")[[i]], na.rm = T)
    fit = lm(mydata[[i]] ~ group + age, data = mydata)
    fvalue = anova(fit)[[4]][1]
    pvalue = round(anova(fit)[[5]][1], 4)
    padjvalue = p.adjust(round(anova(fit)[[5]][1], 4), method = "fdr", n = 78)
    temp = cbind(oimean, oisd, tbimean, tbisd, fvalue, pvalue, padjvalue)
    table = rbind(table, temp)
}
table <- table[order(table$pvalue), ]
```

```{r, echo = FALSE}
library(knitr)
kable(table, align = "ccccccc", digits = 2, col.names = c("OI mean", "OI SD", 
    "TBI mean", "TBI SD", "F", "p (unadj)", "p (FDR)"))
```

\pagebreak

## Geodesic Depth

```{r, include=FALSE}
setwd("/Volumes/wasatch/data/stats/R21/mindboggle/")
mydata = read.table("geodesic_depth_per_gyrus_label.csv", sep = ",", 
    header = T)
clist = colnames(mydata)[3:length(mydata)]
for (i in clist)
{
    outlier(mydata, i)
}
demogr = read.table("/Volumes/wasatch/data/analyses/R21/demographics/R21_demographics.txt", 
    sep = ",", header = T)
mydata = merge(demogr, mydata, by = "studyid", all.y = T)
mydata$group = relevel(mydata$group, "oi")
table = data.frame()
for (i in 6:(length(mydata)))
{
    oimean = colMeans(subset(mydata, group == "oi")[i], na.rm = T)
    oisd = sd(subset(mydata, group == "oi")[[i]], na.rm = T)
    tbimean = colMeans(subset(mydata, group == "tbi")[i], na.rm = T)
    tbisd = sd(subset(mydata, group == "tbi")[[i]], na.rm = T)
    fit = lm(mydata[[i]] ~ group + age, data = mydata)
    fvalue = anova(fit)[[4]][1]
    pvalue = round(anova(fit)[[5]][1], 4)
    padjvalue = p.adjust(round(anova(fit)[[5]][1], 4), method = "fdr", n = 78)
    temp = cbind(oimean, oisd, tbimean, tbisd, fvalue, pvalue, padjvalue)
    table = rbind(table, temp)
}
table <- table[order(table$pvalue), ]
```

```{r, echo = FALSE}
library(knitr)
kable(table, align = "ccccccc", digits = 2, col.names = c("OI mean", "OI SD", 
    "TBI mean", "TBI SD", "F", "p (unadj)", "p (FDR)"))
```

\pagebreak

## Curvature

```{r, include=FALSE}
setwd("/Volumes/wasatch/data/stats/R21/mindboggle/")
mydata = read.table("curvature_per_gyrus_label.csv", sep = ",", 
    header = T)
clist = colnames(mydata)[3:length(mydata)]
for (i in clist)
{
    outlier(mydata, i)
}
demogr = read.table("/Volumes/wasatch/data/analyses/R21/demographics/R21_demographics.txt", 
    sep = ",", header = T)
mydata = merge(demogr, mydata, by = "studyid", all.y = T)
mydata$group = relevel(mydata$group, "oi")
table = data.frame()
for (i in 6:(length(mydata)))
{
    oimean = colMeans(subset(mydata, group == "oi")[i], na.rm = T)
    oisd = sd(subset(mydata, group == "oi")[[i]], na.rm = T)
    tbimean = colMeans(subset(mydata, group == "tbi")[i], na.rm = T)
    tbisd = sd(subset(mydata, group == "tbi")[[i]], na.rm = T)
    fit = lm(mydata[[i]] ~ group + age, data = mydata)
    fvalue = anova(fit)[[4]][1]
    pvalue = round(anova(fit)[[5]][1], 4)
    padjvalue = p.adjust(round(anova(fit)[[5]][1], 4), method = "fdr", n = 78)
    temp = cbind(oimean, oisd, tbimean, tbisd, fvalue, pvalue, padjvalue)
    table = rbind(table, temp)
}
table <- table[order(table$pvalue), ]
```

```{r, echo = FALSE}
library(knitr)
kable(table, align = "ccccccc", digits = 2, col.names = c("OI mean", "OI SD", 
    "TBI mean", "TBI SD", "F", "p (unadj)", "p (FDR)"))
```